FROM alpine

LABEL maintainer="Alexandre Buisine <alexandrejabuisine@gmail.com>"
LABEL version="4.9.45-1"

RUN apk add --no-cache bash

ENV KERNEL_VERSION=4.9.45-rancher EXTRA_TAG=gpu

COPY resources/extra.sh /usr/local/bin/extra.sh
COPY resources/extras-${EXTRA_TAG}.tar.gz /

RUN chmod +x /usr/local/bin/extra.sh

CMD [ "extra.sh" ]